version: "3.8"

services:
  minio:
    image: minio/minio:latest
    command: server /data --address 0.0.0.0:9000 --console-address 0.0.0.0:9001
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console web
    environment:
      MINIO_ROOT_USER:     "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_BROWSER:       "on"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
