app = "omnicast-minio"
primary_region = "gru"

[build]
  image = "minio/minio:latest"

[compute]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1

# Monte apenas um volume (Fly.io suporta apenas 1 volume por máquina)
[[mounts]]
  source      = "omnicast_minio_data_1"
  destination = "/export1"

[env]
  MINIO_ROOT_USER = "minioadmin"
  MINIO_ROOT_PASSWORD = "minioadmin123"
  MINIO_BROWSER    = "on"
  MINIO_CACHE_DRIVES = "/export1"
  MINIO_CACHE_EXCLUDE = "*.pdf;*.doc;*.docx;*.txt"
  MINIO_CACHE_EXPIRY = "90h"
  MINIO_CACHE_MAXUSE = "80"

[processes]
  app = "minio server /export1 --address 0.0.0.0:9000 --console-address 0.0.0.0:9001"

[[services]]
  internal_port = 9000
  protocol      = "tcp"
  processes     = ["app"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port     = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "30s"
    timeout  = "5s"
    grace_period = "10s"
    restart_limit = 3

[[services]]
  internal_port = 9001
  protocol      = "tcp"
  processes     = ["app"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port     = 9001
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "30s"
    timeout  = "5s"
    grace_period = "10s"
    restart_limit = 3
