app = "omnicast-minio"
primary_region = "gru"

[build]
  image = "minio/minio:latest"

# Monte apenas um volume (Fly.io suporta apenas 1 volume por máquina)
[[mounts]]
  source      = "omnicast_minio_data_1"
  destination = "/export1"

[env]
  MINIO_ACCESS_KEY = "minioadmin"
  MINIO_SECRET_KEY = "minioadmin123"
  MINIO_BROWSER    = "on"

[processes]
  app = "minio server /export1 --console-address \":9001\""

[[services]]
  internal_port = 9000
  protocol      = "tcp"
  processes     = ["app"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port     = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout  = "2s"
    grace_period = "1s"
    restart_limit = 0

[[services]]
  internal_port = 9001
  protocol      = "tcp"
  processes     = ["app"]
  
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port     = 9001
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout  = "2s"
    grace_period = "1s"
    restart_limit = 0
